# Generated by Django 4.2.11 on 2024-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_referente_cadastro', models.CharField(max_length=50)),
                ('link_referente_produto', models.CharField(max_length=50)),
                ('link_referente_receita', models.CharField(max_length=50)),
                ('link_referente_cliente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Defenir nomes dos links',
            },
        ),
    ]
